
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('C:\\Users\\admin\\Python-Projects\\07_Pandas\\08_SalesDataAnalysis\\sales_data.csv')
# print(df)

#Total sales revenue (Hint: create Revenue = Quantity × Price)
df["Revenue"] = df['Quantity']*df['Price']

print(f'Total Sales Revenue: {df["Revenue"].sum()}\n')

print(f'Highest Revenue is generated by: {df["Product"][df["Revenue"] == df["Revenue"].max()].iloc[0]}\n')

print(f'Region with highest revenue: {df['Region'][df['Revenue'] == df['Revenue'].max()].iloc[0]}\n')

print(f'Category that sold the least is: {df['Category'][df['Revenue'] ==df['Revenue'].min()].iloc[0]}\n')

print(f'The average order value is {df['Revenue'].mean()}\n')

df_sorted = df.sort_values(by ='Revenue',ascending=False)
print(f'Top 5 orders are \n {df_sorted.head(5)}\n')

#summary table

category_summary = (
    df.groupby("Category")
    .agg(
        Total_Revenue=("Revenue", "sum"),
        Total_Quantity=("Quantity", "sum"),
        Total_Orders=("OrderID", "count"),
    )
    .sort_values("Total_Revenue", ascending=False)
)

region_summary = (
    df.groupby("Region")
    .agg(
        Total_Revenue=("Revenue", "sum"),
        Total_Quantity=("Quantity", "sum"),
        Total_Orders=("OrderID", "count"),
    )
    .sort_values("Total_Revenue", ascending=False)
)

product_summary = (
    df.groupby("Product")
    .agg(
        Total_Revenue=("Revenue", "sum"),
        Total_Quantity=("Quantity", "sum"),
        Total_Orders=("OrderID", "count"),
    )
    .sort_values("Total_Revenue", ascending=False)
)

##Visualizations
# Revenue by region
plt.figure(figsize=(8, 5))

plt.bar(
    region_summary.index,
    region_summary["Total_Revenue"]
)

plt.title("Revenue by Region")
plt.xlabel("Region")
plt.ylabel("Total Revenue")
plt.tight_layout()


plt.show()


# Revenue by product
plt.figure(figsize=(10, 5))

plt.bar(
    product_summary.index,
    product_summary["Total_Revenue"]
)

plt.title("Revenue by Product")
plt.xlabel("Product")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.tight_layout()



plt.show()
##Insights

print('East region generated the highest revenue, making it the strongest performing region.\n')

print('The product with the highest revenue is Laptop, indicating its popularity and strong sales performance.\n')

print('Electronics generates more revenue than Furniture, suggesting that the electronics category is more profitable.\n')

print('Headphones sold the highest number of units but contributed less revenue than laptops.\n')

print('Revenue is concentrated in a small number of high-value products like laptops and phones.\n')


### Recommendations

print('Increase inventory and marketing efforts for laptops because they contribute the highest revenue.')

print('Study why the East region performs well and apply similar strategies in other regions.')

print('Bundle low-priced products such as headphones with laptops to increase average order value.')

print('Introduce promotions for Furniture to improve sales performance.')

print('Continue monitoring regional sales trends to identify opportunities for growth.')