import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('C:\\Users\\admin\\Python-Projects\\07_Pandas\\08_SalesDataAnalysis\\sales_data.csv')
# print(df)

#Total sales revenue (Hint: create Revenue = Quantity × Price)
df["Revenue"] = df['Quantity']*df['Price']

print(f'Total Sales Revenue: {df['Revenue'].sum()}')

print(f'Highest Revenue is generated by: {df["Product"][df['Revenue'] == df['Revenue'].max()].iloc[0]}')

print(f'Region with highest revenue: {df['Region'][df['Revenue'] == df['Revenue'].max()].iloc[0]}')

print(f'Category that sold the least is: {df['Category'][df['Revenue'] ==df['Revenue'].min()].iloc[0]}')

print(f'The average order value is {df['Revenue'].mean()}')

df_sorted = df.sort_values(by ='Revenue',ascending=False)
print(f'Topr 5 orders are \n {df_sorted.head(5)}')

#summary table
summary_table = df.groupby('Category').agg(Total_Revenue = ('Revenue','sum'), Total_Quantity = ('Quantity','sum'), Total_Orders = ('OrderID','count'))
print(summary_table)

summary_table_region  = df.groupby('Region').agg(Total_revenue = ('Revenue','sum'), Total_Quantity = ('Quantity','sum'), Total_Orders = ('OrderID','count'))
print(summary_table_region)

print('Product summary')
summary_table_product  = df.groupby('Product').agg(Total_revenue = ('Revenue','sum'), Total_Quantity = ('Quantity','sum'), Total_Orders = ('OrderID','count'))
print(summary_table_product.sort_values(by='Total_Orders',ascending=False))